
import "./globals.css"

import { NextAuthProvider, ThemeProvider } from "./providers"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <ThemeProvider>
      <NextAuthProvider>
        {children}
      </NextAuthProvider>
    </ThemeProvider>
  )
}
