import { DesktopNav } from "./components/ui/nav/DesktopNav"
import "./globals.css"

import { globalTokens as $ } from "./globalTokens.stylex"
import * as stylex from "@stylexjs/stylex"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html {...stylex.props(styles.html, styles.reset)} lang="en">
      <body {...stylex.props(styles.reset, styles.body)}>
        <div {...stylex.props(styles.desktop)}>
          <DesktopNav />
        </div>
        <div {...stylex.props(styles.mobile)}>
          <DesktopNav />
        </div>
        {children}
      </body>
    </html>
  )
}

const DARK = "@media (prefers-color-scheme: dark)"
const fgColor = `rgba(${$.foregroundR}, ${$.foregroundG}, ${$.foregroundB}, 1)`

const media = {
  mobile: "@media (max-width: 900px)",
}

const styles = stylex.create({
  html: {
    colorScheme: "light dark"
  },
  reset: {
    minHeight: "100%",
    margin: 0,
    padding: 0,
  },
  body: {
    color: fgColor,
    backgroundColor: {
      default: "linear-gradient(to bottom, rgb(214, 219, 220), white)",
      [DARK]: "linear-gradient(to bottom, rgb(20, 22, 27), black)",
    },
    fontFamily: $.fontSans,
  },
  desktop: {
    display: {
      default: "block",
      [media.mobile]: "none"
    },
  },
  mobile: {
    display: {
      default: "none",
      [media.mobile]: "block"
    },
  }
})
